CREATE TABLE IF NOT EXISTS Genre (
	id SERIAL PRIMARY KEY,
	name VARCHAR(80) NOT NULL	 
);

CREATE TABLE IF NOT EXISTS Artist (
	id SERIAL PRIMARY KEY, 
	name VARCHAR (80) NOT NULL
);

CREATE TABLE IF NOT EXISTS ArtistGenre (
	artist_id INTEGER REFERENCES Artist(id),
	Genre_id INTEGER REFERENCES Genre(id),
	CONSTRAINT pk_AG PRIMARY KEY (Artist_id, Genre_id)
);

CREATE TABLE IF NOT EXISTS Album (
	id SERIAL PRIMARY KEY, 
	name VARCHAR (80) NOT NULL, 
	year_album INTEGER
); 

CREATE TABLE IF NOT EXISTS ArtistAlbum (
	artist_id INTEGER NOT NULL REFERENCES Artist(id),
	album_id INTEGER  NOT NULL REFERENCES Album(id),
	CONSTRAINT pk_AA PRIMARY KEY (Artist_id, Album_id)	
);

CREATE TABLE IF NOT EXISTS Track (
	id SERIAL PRIMARY KEY, 
	name VARCHAR(80) NOT NULL, 
	time_track_sec INTEGER NOT NULL,
	album_id INTEGER NOT NULL REFERENCES Album(id)
);

CREATE TABLE IF NOT EXISTS Collection (
	id SERIAL PRIMARY KEY,
	name VARCHAR(80) NOT NULL,
	year_col VARCHAR(80) NOT NULL,
	track_id INTEGER NOT NULL REFERENCES Track(id)
);



	
